# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-java-app
  labels:
    app.kubernetes.io/name: sample-java-app
    helm.sh/chart: sample-java-app-1.0.0-rc0.0.2
    app.kubernetes.io/instance: sample-java-app
    app: sample-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-java-app
  template:
    metadata:
      labels:
        app: sample-java-app
    spec:
      containers:
      - name: sample-java-app
        image: "image-registry.openshift-image-registry.svc:5000/ci/sample-java-app:0.0.16"
        ports:
        - containerPort: 9080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true
